language: cpp
compiler: gcc
matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      addons:
        apt:
            update: true
            sources:
                - ubuntu-toolchain-r-test
            packages:
                - cmake
                - gcc-arm-none-eabi
                - binutils-arm-none-eabi
                - u-boot-tools
                - gcc-4.9
                - g++-4.9
      env:
        - CCOMPILER=gcc-4.9
        - CXXCOMPILER=g++-4.9
    - os: linux
      dist: xenial
      sudo: required
      addons:
        apt:
            update: true
            sources:
                - ubuntu-toolchain-r-test
            packages:
                - cmake
                - gcc-arm-none-eabi
                - binutils-arm-none-eabi
                - u-boot-tools
                - gcc-5
                - g++-5
      env:
        - CCOMPILER=gcc-5
        - CXXCOMPILER=g++-5
    - os: linux
      dist: xenial
      sudo: required
      addons:
        apt:
            update: true
            sources:
                - ubuntu-toolchain-r-test
            packages:
                - cmake
                - gcc-arm-none-eabi
                - binutils-arm-none-eabi
                - u-boot-tools
                - gcc-8
                - g++-8
      env:
        - CCOMPILER=gcc-8
        - CXXCOMPILER=g++-8
install:
  - if [[ -n "$CCOMPILER" ]]; then export CC=$CCOMPILER; fi
  - if [[ -n "$CXXCOMPILER" ]]; then export CXX=$CXXCOMPILER; fi
      
script:
  - cd ..
  - mkdir build
  - cd build
  - cmake ../sweb
  - make 
  - yes | make x86_32
  - make
  - yes | make x86_32_pae
  - make
  - yes | make arm_rpi2
  - make
  - yes | make arm_icp
  - make
  - yes | make arm_verdex
  - make
