language: cpp
compiler: gcc
#dist: xenial
matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
    - os: linux
      dist: bionic
      sudo: required
      
      
before_install:
  - sudo apt-get update
  - sudo apt-get install make cmake gcc g++ gcc-arm-none-eabi binutils-arm-none-eabi u-boot-tools
script:
  - cd ..
  - mkdir build
  - cd build
  - cmake ../sweb
  - make 
  - yes | make x86_32
  - make
  - yes | make x86_32_pae
  - make
  - yes | make arm_rpi2
  - make
  - yes | make arm_icp
  - make
  - yes | make arm_verdex
  - make
