language: cpp
compiler: gcc
matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      addons:
        apt:
            update: true
            sources:
                - sourceline: 'ppa:ubuntu-toolchain-r/test'
            packages:
                - cmake
                - gcc-arm-none-eabi
                - binutils-arm-none-eabi
                - u-boot-tools
                - gcc-5
                - g++-5
                - qemu-system-x86
                - qemu-system-arm
      env:
        - CCOMPILER=gcc-5
        - CXXCOMPILER=g++-5
    - os: linux
      dist: xenial
      sudo: required
      addons:
        apt:
            update: true
            sources:
                - sourceline: 'ppa:ubuntu-toolchain-r/test'
            packages:
                - cmake
                - gcc-arm-none-eabi
                - binutils-arm-none-eabi
                - u-boot-tools
                - gcc-6
                - g++-6
                - qemu-system-x86
                - qemu-system-arm
      env:
        - CCOMPILER=gcc-6
        - CXXCOMPILER=g++-6

    - os: linux
      dist: xenial
      sudo: required
      addons:
        apt:
            update: true
            sources:
                - sourceline: 'ppa:ubuntu-toolchain-r/test'
            packages:
                - cmake
                - gcc-arm-none-eabi
                - binutils-arm-none-eabi
                - u-boot-tools
                - gcc-7
                - g++-7
                - qemu-system-x86
                - qemu-system-arm
      env:
        - CCOMPILER=gcc-7
        - CXXCOMPILER=g++-7
                
        
    - os: linux
      dist: xenial
      sudo: required
      addons:
        apt:
            update: true
            sources:
                - sourceline: 'ppa:ubuntu-toolchain-r/test'
            packages:
                - cmake
                - gcc-arm-none-eabi
                - binutils-arm-none-eabi
                - u-boot-tools
                - gcc-8
                - g++-8
                - qemu-system-x86
                - qemu-system-arm
      env:
        - CCOMPILER=gcc-8
        - CXXCOMPILER=g++-8
        
install:
  - if [[ -n "$CCOMPILER" ]]; then export CC=$CCOMPILER; fi
  - if [[ -n "$CXXCOMPILER" ]]; then export CXX=$CXXCOMPILER; fi
      
script:
  - cd ..
  - mkdir build
  - cd build
  - cmake ../sweb
  - cp ../sweb/utils/travis_test.sh .
  - ./travis_test.sh x86_32
  - cp ../sweb/utils/travis_test.sh .
  - ./travis_test.sh x86_32_pae
  - cp ../sweb/utils/travis_test.sh .
  - ./travis_test.sh arm_rpi2
  - cp ../sweb/utils/travis_test.sh .
  - ./travis_test.sh arm_icp
  - cp ../sweb/utils/travis_test.sh .
  - ./travis_test.sh arm_verdex
